[package]
name        = "testkit"
version     = "0.1.0"
publish     = false
edition.workspace      = true
license.workspace      = true
repository.workspace   = true
rust-version.workspace = true

[dependencies]
testcontainers = { workspace = true }
tokio          = { workspace = true }
thiserror      = { workspace = true }
tracing        = { workspace = true }
futures        = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }

[lints]
workspace = true
