//! The fixture interface the acceptance suite is written against.
//!
//! Tests take `&dyn Cluster`, never a concrete container type. That is not
//! abstraction for its own sake — CLAUDE.md's argument is that kaas-lib is the
//! natural conformance harness for the `kaas` *broker*, and that only works if
//! the acceptance suite can be pointed at something other than
//! `apache/kafka:4.3.1` without touching a single test. A hardcoded image in
//! the fixtures would quietly foreclose that.
//!
//! [`ExternalCluster`] is the other half of the bargain: it makes "point the
//! suite at a broker that is already running" a supported mode today, so the
//! seam gets exercised rather than rotting.

use std::fmt;

use futures::future::LocalBoxFuture;

use crate::error::{Error, Result};

/// The captured result of a command run inside a fixture node.
#[derive(Debug, Clone)]
pub struct ExecOutput {
    /// Exit status, if the runtime reported one.
    pub code: Option<i64>,
    /// Captured stdout, lossily decoded as UTF-8.
    pub stdout: String,
    /// Captured stderr, lossily decoded as UTF-8.
    pub stderr: String,
}

impl ExecOutput {
    /// True when the command exited zero.
    pub fn ok(&self) -> bool {
        self.code == Some(0)
    }
}

/// A running Kafka cluster a test can talk to.
///
/// Implementors are responsible for handing back bootstrap addresses that are
/// reachable *from the test process*, which for container fixtures means the
/// host-mapped port rather than the in-container one.
pub trait Cluster: fmt::Debug + Send + Sync {
    /// Bootstrap addresses, `host:port`, reachable from the test process.
    fn bootstrap(&self) -> &[String];

    /// How many broker nodes this cluster has.
    fn nodes(&self) -> usize;

    /// Run `argv` inside node `index`.
    ///
    /// M7's group fixtures are generated by the Kafka shell tools inside the
    /// container rather than by a Rust client, because `librdkafka` has no
    /// KIP-932 share-group support and so cannot produce the share-group
    /// fixture at all. This is the hook that makes that possible.
    ///
    /// Returns [`Error::Unsupported`] for fixtures with nothing to exec into.
    ///
    /// The returned future is deliberately not `Send`: `testcontainers`'
    /// `ExecResult` holds a boxed stream that is `Send` but not `Sync`, so
    /// reading a command's exit status cannot produce a `Send` future. Fixtures
    /// are awaited inline from the test that owns them, so nothing is lost.
    fn exec<'a>(
        &'a self,
        index: usize,
        argv: Vec<String>,
    ) -> LocalBoxFuture<'a, Result<ExecOutput>>;

    /// Bootstrap addresses joined the way every Kafka CLI tool wants them.
    fn bootstrap_csv(&self) -> String {
        self.bootstrap().join(",")
    }
}

/// Run `argv` on `index` and fail unless it exits zero.
///
/// A free function rather than a trait method so `Cluster` stays object-safe
/// with no `where Self: Sized` escape hatches.
pub async fn exec_ok(
    cluster: &dyn Cluster,
    index: usize,
    argv: impl IntoIterator<Item = impl Into<String>>,
) -> Result<ExecOutput> {
    let argv: Vec<String> = argv.into_iter().map(Into::into).collect();
    let display = argv.join(" ");
    let out = cluster.exec(index, argv).await?;
    if out.ok() {
        Ok(out)
    } else {
        Err(Error::Exec {
            argv: display,
            node: index,
            code: out.code,
            stdout: out.stdout,
            stderr: out.stderr,
        })
    }
}

/// A cluster that is already running somewhere else.
///
/// This is how the acceptance suite gets pointed at a `kaas` broker, or at a
/// developer's local cluster, without a container runtime. `exec` is
/// unavailable, so fixtures that shell into the broker (M7's group kinds) will
/// report [`Error::Unsupported`] rather than silently passing.
#[derive(Debug, Clone)]
pub struct ExternalCluster {
    bootstrap: Vec<String>,
    nodes: usize,
}

impl ExternalCluster {
    /// Point at an already-running cluster.
    pub fn new(bootstrap: impl IntoIterator<Item = impl Into<String>>) -> Self {
        let bootstrap: Vec<String> = bootstrap.into_iter().map(Into::into).collect();
        let nodes = bootstrap.len();
        Self { bootstrap, nodes }
    }

    /// Read bootstrap addresses from `KAAS_TEST_BOOTSTRAP`, comma separated.
    ///
    /// Returns `None` when the variable is unset, which is the signal to boot a
    /// container fixture instead.
    pub fn from_env() -> Option<Self> {
        let raw = std::env::var("KAAS_TEST_BOOTSTRAP").ok()?;
        let addrs: Vec<String> = raw
            .split(',')
            .map(str::trim)
            .filter(|s| !s.is_empty())
            .map(str::to_owned)
            .collect();
        if addrs.is_empty() {
            None
        } else {
            Some(Self::new(addrs))
        }
    }
}

impl Cluster for ExternalCluster {
    fn bootstrap(&self) -> &[String] {
        &self.bootstrap
    }

    fn nodes(&self) -> usize {
        self.nodes
    }

    fn exec<'a>(
        &'a self,
        _index: usize,
        _argv: Vec<String>,
    ) -> LocalBoxFuture<'a, Result<ExecOutput>> {
        Box::pin(async {
            Err(Error::Unsupported(
                "external clusters have no container to exec into",
            ))
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn external_cluster_splits_and_trims() {
        let c = ExternalCluster::new(["a:1", "b:2"]);
        assert_eq!(c.bootstrap(), ["a:1".to_string(), "b:2".to_string()]);
        assert_eq!(c.bootstrap_csv(), "a:1,b:2");
        assert_eq!(c.nodes(), 2);
    }
}
