//! M0 acceptance: a real broker in a container, reachable from a test.
//!
//! Run with `cargo test -p testkit -- --ignored` (needs a Docker daemon).
#![allow(
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::panic,
    clippy::indexing_slicing
)]

use std::time::Duration;

use testkit::{BrokerConfig, Cluster};
use tokio::net::TcpStream;

/// Every bootstrap address must accept a bare TCP connection.
async fn assert_all_reachable(cluster: &dyn Cluster) {
    for addr in cluster.bootstrap() {
        let stream = tokio::time::timeout(Duration::from_secs(10), TcpStream::connect(addr))
            .await
            .unwrap_or_else(|_| panic!("timed out connecting to {addr}"))
            .unwrap_or_else(|e| panic!("connecting to {addr}: {e}"));
        assert!(stream.peer_addr().is_ok());
    }
}

#[testkit::integration_test]
async fn single_broker_accepts_a_tcp_connection() {
    let broker = testkit::single_broker().await.unwrap();
    assert_eq!(broker.nodes(), 1);
    assert_eq!(broker.bootstrap().len(), 1);
    assert_all_reachable(&broker).await;
}

#[testkit::integration_test]
async fn three_node_cluster_exposes_three_reachable_brokers() {
    let cluster = testkit::cluster(3).await.unwrap();
    assert_eq!(cluster.nodes(), 3);
    assert_all_reachable(&cluster).await;

    // Distinct host ports, or the fixture has quietly collapsed to one broker.
    let mut addrs = cluster.bootstrap().to_vec();
    addrs.sort();
    addrs.dedup();
    assert_eq!(addrs.len(), 3, "bootstrap addresses must be distinct");
}

#[testkit::integration_test]
async fn exec_reaches_the_bundled_kafka_tools() {
    // M7's fixtures are generated by these tools rather than by a Rust client,
    // so `exec` working is a precondition for that milestone, not a nicety.
    let broker = testkit::single_broker().await.unwrap();
    let out = broker
        .kafka_cli(0, "kafka-topics.sh", ["--list"])
        .await
        .unwrap();
    assert!(out.ok(), "{out:?}");
}

#[testkit::integration_test]
async fn config_builder_reaches_the_broker() {
    // The whole point of taking the builder at M0: prove a non-default
    // property actually lands in the running broker's configuration.
    let broker = testkit::single_broker_with(
        BrokerConfig::new()
            .with_auto_create_topics(true)
            .with_property("num.partitions", "7"),
    )
    .await
    .unwrap();

    let out = broker
        .kafka_cli(
            0,
            "kafka-configs.sh",
            [
                "--describe",
                "--entity-type",
                "brokers",
                "--entity-name",
                "1",
                "--all",
            ],
        )
        .await
        .unwrap();
    assert!(
        out.stdout.contains("num.partitions=7"),
        "stdout was:\n{}",
        out.stdout
    );
}
